CREATE TABLE [dbo].[DimProduct] (
    [ProductKey]            INT             NULL,
    [ProductAlternateKey]   VARCHAR (8000)  NULL,
    [ProductSubcategoryKey] INT             NULL,
    [WeightUnitMeasureCode] CHAR (3)        NULL,
    [SizeUnitMeasureCode]   CHAR (3)        NULL,
    [EnglishProductName]    VARCHAR (8000)  NULL,
    [SpanishProductName]    VARCHAR (8000)  NULL,
    [FrenchProductName]     VARCHAR (8000)  NULL,
    [StandardCost]          DECIMAL (19, 4) NULL,
    [FinishedGoodsFlag]     BIT             NULL,
    [Color]                 VARCHAR (8000)  NULL,
    [SafetyStockLevel]      SMALLINT        NULL,
    [ReorderPoint]          SMALLINT        NULL,
    [ListPrice]             DECIMAL (19, 4) NULL,
    [Size]                  VARCHAR (8000)  NULL,
    [SizeRange]             VARCHAR (8000)  NULL,
    [Weight]                FLOAT (53)      NULL,
    [DaysToManufacture]     INT             NULL,
    [ProductLine]           CHAR (2)        NULL,
    [DealerPrice]           DECIMAL (19, 4) NULL,
    [Class]                 CHAR (2)        NULL,
    [Style]                 CHAR (2)        NULL,
    [ModelName]             VARCHAR (8000)  NULL,
    [EnglishDescription]    VARCHAR (8000)  NULL,
    [FrenchDescription]     VARCHAR (8000)  NULL,
    [ChineseDescription]    VARCHAR (8000)  NULL,
    [ArabicDescription]     VARCHAR (8000)  NULL,
    [HebrewDescription]     VARCHAR (8000)  NULL,
    [ThaiDescription]       VARCHAR (8000)  NULL,
    [GermanDescription]     VARCHAR (8000)  NULL,
    [JapaneseDescription]   VARCHAR (8000)  NULL,
    [TurkishDescription]    VARCHAR (8000)  NULL,
    [StartDate]             DATETIME2 (3)   NULL,
    [EndDate]               DATETIME2 (3)   NULL,
    [Status]                VARCHAR (8000)  NULL
);
GO

